- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.css
- front-end/src/App.js
- front-end/src/Navbar.css
- front-end/src/Navbar.js
- front-end/src/NavbarRightSignedout.js
- Simple navbar added
- Added bootstrap dependencies
- Edited App.js just to have something to look at
Resolves #12
> Added bootstrap to dependencies, navbar component

- front-end/package-lock.json
- front-end/package.json
- Fixed syntax errors in package-lock.json and package.json incurred by merging #62 
- Fixes #69
> added syntactically correct package-lock.json and package.json

- front-end/package-lock.json
- front-end/package.json
Reverts agile-dev-assignments/project-setup-team-ntobo-global#70
> Revert "added syntactically correct package-lock.json and package.json"

- front-end/src/Timestamp.css
- front-end/src/Timestamp.js
> Implementing timestamp component task from user story #66

- front-end/src/SmallRecipePreview.css
- front-end/src/SmallRecipePreview.js
> Add timestamp and modify props for small recipe preview

- front-end/src/LargeRecipePreview.css
- front-end/src/LargeRecipePreview.js
> Add timestamp and modify props for large recipe preview

- front-end/src/App.js
- front-end/src/LargeRecipePreview.js
- front-end/src/RecipeList.css
- front-end/src/RecipeList.js
RecipeList component. I realized I needed to reuse this for recipebox and the feedpage and figure it will come in useful for browse page and such
resolves #79
> Setting up recipelist component for recipebox and feedpage

- front-end/src/Comment.css
- front-end/src/Comment.js
> Implementing comment component task from user story #28

- front-end/src/HamburgerNotSignedIn.css
- front-end/src/HamburgerNotSignedIn.js
Added comments to the not signed-in hamburger menu and the corresponding css file for readability.
> Commented code

- front-end/src/App.js
This branch makes changes to App.js. Every possible route (let me know if I missed any or should rename any) is included. When you implement a page, simply go to App.js and uncomment the corresponding route. Then, insert the page's component tag in between the route tags. (See the recipe page route for an example).
resolves #58
> Setting up client-side routes using browser router

- front-end/src/ComboBoxSearchBar.css
- front-end/src/ComboBoxSearchBar.js
- Added autofill (combo-box) search bar component for tags and users
- resolves #3
> Added autofill (combo-box) search bar component

- front-end/src/FeedPage.js
- front-end/src/RecipeList.css
- front-end/src/RecipeList.js
Made a cleaner foreach loop that looks at `props.recipes` passed in from the page it is derived from (e.g. `FeedPage.js` generates the proper array for the feed and passes it to `RecipeList.js`).
If I'm missing a prop that's meant to be passed in or something, comment below 👍
> RecipeList component cleanup

- front-end/src/FollowButton.css
- front-end/src/FollowButton.js
> implement follow button

- front-end/src/App.js
- front-end/src/BrowseRecipesPage.css
- front-end/src/BrowseRecipesPage.js
resolves #24 
Ignore the crappy css on the tag buttons; I figure we can fix it when we fix site-wide.
> Implementing browse recipes page

- front-end/src/ProfileHeader.css
- front-end/src/ProfileHeader.js
I changed the layout of the profile header component. It doesn't quite follow the wireframe. Let me know if I should change it back to the layout specified in the wireframe (I think this layout looks much better).
> Modify props and user object to match schema, remove edit button, and modify css and layout

- front-end/src/App.js
- front-end/src/SignInForm.css
- front-end/src/SignInForm.js
resolves #8 
Just made a new branch to fix git issues.
Prior PR had comments from Ashley: 
"Looks good, just a couple of things that need to be modified:
The href for the Create Account link should be '/create-account'
Add the error message to the jsx and change its visibility via className and css (we can implement the css later in App.css)
There's a syntax error- error vs errors
Can we put the Create Account link on it's own line?"
^ Fixed all the changes.
> New branch - fixing git issues and completed sign-in

- front-end/src/BrowseRecipesPage.js
- front-end/src/Comment.js
- front-end/src/FeedPage.js
- front-end/src/RecipePage.js
> Use picsum to generate images for backup data

- front-end/src/App.js
- front-end/src/FollowButton.js
- front-end/src/ProfilePage.js
- front-end/src/RecipePage.js
- front-end/src/SignInModal.js
> Display sign-in modal when a not signed-in user attempts to like, comment, or follow

- front-end/src/BrowseRecipesPage.css
- front-end/src/BrowseRecipesPage.js
- front-end/src/TagButton.css
- front-end/src/TagButton.js
> Move TagButton component to separate file and update its css

- front-end/src/App.js
- front-end/src/BrowseUsersPage.css
- front-end/src/BrowseUsersPage.js
> Implemented browse users page

- front-end/src/SignInForm.js
Changed so we have consistency with button class names.
> changed className to submitButton

- front-end/src/App.js
- front-end/src/FollowersPage.css
- front-end/src/FollowersPage.js
resolves #44 
Implemented page for followers - styling is todo.
> User story/42/task/44/implement followers page

- front-end/src/App.js
- front-end/src/FollowingPage.css
- front-end/src/FollowingPage.js
resolved #45 
Implemented page for following - styling is todo.
> User story/43/task/45/implement following page

- front-end/src/App.js
- front-end/src/AppSettings.css
- front-end/src/AppSettings.js
> Added app settings page

- front-end/src/App.js
- front-end/src/BlockedUsers.css
- front-end/src/BlockedUsers.js
- front-end/src/SmallUserPreview.js
> Added blocked users page

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/NewRecipePage.js
Currently, there is no form validation for this page.
To be implemented later:
- Disable `Post Recipe` button if any field is empty
- Validate form and display appropriate error messages for each field
resolves #15
> Implement new recipe page

- front-end/src/ComboBoxSearchBar.css
- front-end/src/ComboBoxSearchBar.js
- Added adjacent icons similar to that of KeywordSearchBar
- Changed placeholders to deter users from typing "#" or "@"
> ComboBox changes

- front-end/src/RecipeList.css
Removes azure from recipelist.css
> Remove blue from recipelist

- back-end/app.js
- back-end/package-lock.json
- back-end/package.json
- back-end/server.js
> Set up Express.js back-end

- back-end/app.js
- back-end/package-lock.json
- back-end/package.json
Added dependencies for and required:
- nodemon
- morgan
- multer
- axios
- dotenv
Set up middleware for:
- morgan
- bodyparser
resolves #150
> Add some dev and middleware dependencies 

- back-end/app.js
> Implement route handler for GET requests to /recipe

- back-end/app.js
> Implement route handler for GET requests to /comments

- back-end/app.js
> route handler for get /usersbyname

- back-end/app.js
> route handler for get /usersbyid

- back-end/app.js
- back-end/package-lock.json
- back-end/package.json
- back-end/server.js
> Switch server to port 4000 and fix CORS error

- back-end/app.js
> Implement route handler for POST requests to /comment

- back-end/app.js
> Implement route handler for GET /userbyid

- back-end/app.js
> Implement route handler for GET /userbyslug

- back-end/app.js
> Implement route handler for GET /tags

- back-end/app.js
> Implement route handler for GET /filteredrecipes

- front-end/src/BrowseRecipesPage.js
> Make GET /tags request in BrowseRecipesPage.js

- front-end/src/RecipePage.js
> Make GET /comments request from RecipePage.js

- front-end/src/Comment.js
> Make GET /userbyid request from Comment.js

- back-end/app.js
> Implement route handler for POST /likerecipe

- back-end/app.js
> Implement route handler for GET /recipesbyuser

- back-end/app.js
> Route handler for POST requests to /blockuser

- front-end/src/App.js
- front-end/src/BrowseUsersPage.js
Branched from master
resolves #240
> Search bar - browse users

- front-end/src/FollowersPage.js
Branched from master
resolves #242
> Search bar - followers

- front-end/src/FollowingPage.js
Branched from master
resolves #241
> Search bar - following

- front-end/src/ProfilePage.js
> Make GET /userbyslug request in ProfilePage.js

- front-end/src/ProfilePage.js
> Make GET /recipesbyuser request in ProfilePage.js

- front-end/src/BrowseRecipesPage.js
> Make GET /filteredrecipes request from BrowseRecipesPage.js

- back-end/app.js
- front-end/src/NewRecipePage.js
> Implement POST /newrecipe route handler

- front-end/public/uploads/.gitignore
- front-end/src/NewRecipePage.js
> Make POST /newrecipe request in NewRecipePage.js

- front-end/src/BrowseRecipesPage.js
- front-end/src/LargeRecipePreview.js
- front-end/src/RecipePage.js
> Grab tag from query string when tag link clicked

- back-end/.eslintrc.json
- back-end/.prettierrc
- back-end/app.js
- back-end/package-lock.json
- back-end/package.json
- back-end/server.js
> add ESLint with Prettier and Airbnb style configurations and add linted backend files

- back-end/app.js
- front-end/src/AppSettings.js
> Implemented route handler for /notificationsettings

- front-end/src/BrowseUsersPage.js
- front-end/src/FollowersPage.js
- front-end/src/FollowingPage.js
resolves #277 
A new branch bc git hates me, but fixed all changes!
> new branch as usual, changes to followers, following, browse users

- back-end/app.js
resolves #191 
Fixed the comments you left before, created a new branch because of git rebasing problems.
> New branch, implemented route /updateuserinfo

- front-end/src/AppSettings.css
- front-end/src/AppSettings.js
- front-end/src/ComboBoxSearchBar.js
- front-end/src/SmallUserPreview.js
> GET request to /usersbyid from frontend (AppSettings.js)

- back-end/app.js
- back-end/package-lock.json
> Fix back-end/package-lock.json

- front-end/package-lock.json
- front-end/package.json
> Fixing front-end/package.json to fix npm install errors

- back-end/app.js
> Fix CORS error once and for all

- back-end/app.js
- front-end/src/AppSettings.js
- Resolves #171 
- also updated route handler for post request to /blockuser to change to signed-in user and blocked users' following and followers arrays
> POST request to /blockuser via AppSettings.js

- back-end/test/getFilteredRecipes.test.js
> Write unit tests for GET /filteredrecipes route handler

- back-end/app.js
resolves #216 
Fixed the comments!
> Fixed comments for route

- back-end/test/getTags.test.js
> Write unit tests for GET /tags route handler

- front-end/src/CreateAccountPage.css
- front-end/src/CreateAccountPage.js
resolves #210 
Form validation and error messages now work!
> Form validation for create account

- CONTRIBUTING.md
Added running instructions for front-end and back-end components, which is whatever we do when testing.
This resolves #322
> Update contributing with building and running instructions

- back-end/app.js
- front-end/src/AppSettings.js
> POST request to /notificationsettings from AppSettings.js

- back-end/app.js
- back-end/test/postComment.test.js
On failure:
On success:
Checks to make sure comment has all fields, pretty much.
resolves #307
> Unit test for comment posting

- back-end/test/getUserBySlug.test.js
> Unit tests for /userbyslug

- front-end/src/CreateAccountPage.js
> Fixed warning for CreateAccountPage

- back-end/app.js
- front-end/src/EditProfilePage.js
resolves #192 
I added in the POST request for /updateuserinfo, but didn't change any of the validation for the page yet. (I figured images and anything being edited isn't required to be changed)
> Implemented POST /updateuserinfo

- back-end/test/getUsersByName.test.js
> unit tests for get /usersbyname

- back-end/app.js
- front-end/src/RecipeBoxPage.js
Made a call to `/filteredrecipes` that is identical to BrowseUsersPage.js except that it also passes the array of liked recipes. 
This resolves #202
> Use filtered recipes for recipebox page with liked array passed in

- front-end/src/FollowingPage.js
> GET request to /usersbyid from FollowingPage.js

- back-end/test/getRecipe.test.js
> Unit tests for GET /recipe route handler

- back-end/test/postBlockUser.test.js
- front-end/src/AppSettings.js
> Unit testing for POST /blockuser route handler

- front-end/src/AppSettings.js
- front-end/src/BrowseRecipesPage.js
- front-end/src/BrowseUsersPage.js
- front-end/src/Comment.js
- front-end/src/FeedPage.js
- front-end/src/FollowersPage.js
- front-end/src/FollowingPage.js
- front-end/src/ProfilePage.js
- front-end/src/RecipeBoxPage.js
- front-end/src/RecipePage.js
If you need to test a page and Mockaroo is down, you can stop the error component from rendering (and instead render the page with our mock data) by commenting out this line in the page's get requests: `setReqError(true)`
resolves #334
> Render error component when a request responds with an error

- back-end/test/getFilteredRecipes.test.js
> Add a unit test to check if the returned objects are recipe objects

- front-end/src/App.js
- front-end/src/EditProfilePage.js
- front-end/src/FeedPage.js
- front-end/src/HamburgerSignedIn.js
- front-end/src/RecipeBoxPage.js
- front-end/src/SmallUserPreview.js
- Removed warnings from front-end compilation
- Put something to resolve mockaroo failing and showing error component on feed page, but this will be overridden in another PR (I felt it necessary given that the feed page is the main page)
> Warnings Be-Gone™

- back-end/app.js
- front-end/src/AppSettings.js
> Commented out Posts Notifications in AppSettings.js and backend app.js

- front-end/src/RecipePage.js
- Submit a comment to the post request
- Someone did most of the work in terms of setting up data to send, so retroactive thank you!
- Here's the console log from the route handler
> POST req to /comment

- front-end/src/RecipePage.js
- Creates a POST request to update the like recipes on the backend by posting to the api
- Here are the req details posted to console from the route handler, but I removed it in this PR
> POST req to like recipe handler from front-end

- back-end/app.js
- back-end/db.js
- front-end/src/NewRecipePage.js
> Implement save new recipes to database and update tags collection

- back-end/app.js
- back-end/test/postBlockUser.test.js
- back-end/test/postNotificationSettings.test.js
- resolves #301 
- also includes minor fixes to POST /blockuser route handler and respective unit tests
> Unit tests for POST /notificationsettings route handler

- back-end/app.js
- front-end/src/BrowseRecipesPage.js
> Implementing find all tags (that aren't blocked) from database for GET /tags

- front-end/src/Timestamp.js
> Fix timestamp component bug

- back-end/app.js
> Implementing find recipes from database that match filter for GET /filteredrecipes

- back-end/test/getRecipesByUser.test.js
- Unit test for `/recipesbyuser` route handler
> Unit test for /recipesbyuser route handler

- back-end/app.js
- front-end/src/BrowseUsersPage.js
> Implement find filtered users from database for GET /usersbyname

- back-end/app.js
> database functionality for get /userbyslug

- back-end/app.js
> database functionality get /usernametaken

- back-end/app.js
> implemented finding users from database GET /usersbyid

- front-end/src/FollowButton.js
- front-end/src/ProfilePage.js
> add POST request to /followuser from Follow Button

- front-end/src/FollowButton.js
- front-end/src/ProfilePage.js
Reverts agile-dev-assignments/project-setup-team-ntobo-global#395
> Revert "add POST request to /followuser from Follow Button"

- front-end/src/FollowButton.js
- front-end/src/ProfilePage.js
> implement post request to /follow user from follow button

- back-end/app.js
- front-end/src/RecipePage.js
> Implementing update recipe's likes and user's liked in database for POST /likerecipe

- back-end/app.js
- front-end/src/RecipePage.js
> Implement find comments from database for GET /comments

- back-end/app.js
- front-end/src/BrowseRecipesPage.css
- front-end/src/BrowseRecipesPage.js
> Implement find and display recommended recipes for browse recipes page

- back-end/app.js
> Implement find user by id from database

- back-end/app.js
- front-end/src/FollowButton.js
Unable to thoroughly test, but appears to be fine from existing data (e.g. if I log the request info, it successfully shows that `req.query.userID` is the matching ID to the mockaroo user pulled from). In other words, it pulls a value from the intended spot that matches the intended value.
Question remains: it appears the database shows `ObjectId("####")`... does that change anything?
> User story/347/task/368/recipesbyuser

- back-end/app.js
- front-end/src/BrowseRecipesPage.js
- front-end/src/BrowseUsersPage.css
- front-end/src/BrowseUsersPage.js
> Implement find recommended users from database

- back-end/app.js
- front-end/src/FeedPage.js
- Will not run unless `FollowButton.js` has the import added back in (going to check that PR right after I write this), but once that is imported (or done manually on your end) it runs fine.
Additions:
- `/feedrecipes` will load recipes posted within the last two weeks from followed users (back-end/app.js)
- If following list is `0`, request is never made and specific error component loaded (front-end/FeedPage.js)
Since things aren't totally together, here are the following tests to ensure the db queries work and component loads:
- Isolating date, we see recipes loaded from within last two weeks (if I changed to last day it shows just the one)
- If the following list is set to a static list (e.g. id of user `ash`) it shows only recipes by `ash` (and thus not from `Mobkinz`, the other user …
> Feed Page pulls from database

- back-end/app.js
- front-end/src/RecipePage.js
> Database POST /comment

- front-end/src/FollowButton.js
- front-end/src/ProfilePage.js
import statement removed during merge
resolves #219
> add back import axios to FollowButton.js

- back-end/app.js
- front-end/src/AppSettings.js
- front-end/src/BrowseRecipesPage.js
- Changes blockedTags array in database for POST /blocktag
- Prevents signed-in user's blocked tags from appearing from Browse Recipes Page feed
- resolves #286
> Implement update blockedTags array in database for POST /blocktag

- back-end/app.js
- back-end/package-lock.json
- back-end/package.json
- Setting up credentials and SMTP connection for sending email notifications from recipeboxupdate@gmail.com
- Actually allowing notifications to be sent for liked recipes
> Setting up SMTP connection for sending email notifications and implementing send email notifications for liked recipes

- back-end/app.js
- front-end/src/App.js
- front-end/src/FollowButton.js
- front-end/src/ProfilePage.js
> Implement update following and followers on follow in database and fix follow button text

- back-end/app.js
- front-end/src/App.js
- front-end/src/RecipePage.js
> Fix heart image bug and update user and recipe on like

- back-end/app.js
- back-end/db.js
- front-end/src/LargeRecipePreview.js
- front-end/src/NewRecipePage.js
- front-end/src/ProfilePage.css
- front-end/src/ProfilePage.js
- front-end/src/RecipePage.js
- front-end/src/SmallRecipePreview.js
> Change recipe schema so user field stores the author's _id

- back-end/app.js
- allows for email notifications to be sent for comments and follows
- fixes likes notifications
- resolves #360
> implementing functionality and HTML formatting for all email notifications

- back-end/app.js
- back-end/test/postNewRecipe.test.js
resolves #306 
Ashley - I want you to check the changes I made to NewRecipe.js
I removed the .split(",") since those fields were already arrays and didn't need to be split by a comma. I was getting an error on the tests otherwise.
> unit tests for post /newrecipe

- front-end/src/RecipePage.js
resolves #223 
Blocked recipe should show an error component "Couldn't load recipe"
> prevent user from viewing full recipes of blocked user

- back-end/test/postNewRecipe.test.js
> commented out post /newrecipe unit tests

- back-end/app.js
- front-end/src/pages/recipepages/components/LargeRecipePreview.css
- front-end/src/pages/recipepages/recipe/RecipePage.css
> Fixing GET /usersbyid route handler and recipe tag css

- back-end/package.json
Added --exit to nyc mocha in the package.json so running npm test doesn't execute forever.
resolves #495
> added --exit to nyc mocha

- back-end/app.js
- back-end/package-lock.json
- back-end/package.json
- front-end/src/pages/recipepages/recipe/RecipePage.css
- front-end/src/pages/recipepages/recipe/RecipePage.js
> Implement delete recipe

- back-end/app.js
- back-end/test/postBlockUser.test.js
- resolves #470  
- resolves #508 
- when testing with `npm test` be aware that there are failing tests on this branch (outside of commit(s) here) that are misnamed `Testing POST to /blockusers API` (bc of me forgetting to change that part of a large chunk of code that I copy pasted somewhere during sprint 2) that do not reflect the tests here. `mocha test/postBlockUser.test.js` from `back-end` if you don't want to confuse yourself
> Fixing postBlockUser.test.js

- back-end/app.js
- front-end/src/gencomponents/ErrorComponent.js
- front-end/src/pages/recipepages/feed/FeedPage.js
- No longer says invalid username if form data is valid (issue with back-end validation/sanitation)
- Adjust error component so that it routes to `/` for those not logged in
> Fixes for error component and signup page

- back-end/test/getRecipesByUser.test.js
resolves #488 
Needs an existing userID from the database to pass (I'm using ash's).
> updated test get /recipesbyuser

- back-end/test/getUsers.test.js
> unit tests for get /users

- front-end/package-lock.json
- front-end/package.json
- front-end/src/gencomponents/ImageCropModal.css
- front-end/src/gencomponents/ImageCropModal.js
- front-end/src/pages/recipepages/newrecipe/NewRecipePage.js
- front-end/src/pages/userpages/profilepages/editprofile/EditProfilePage.js
- Resolves #464 
- As of now, cropped images are exported as blobs (binary data w/type) rather than .pngs or .jpegs. Can change this if needed, but functionality is all there
> Allowing user to crop recipe picture and profile picture uploads

- back-end/test/postNotificationSettings.test.js
> Fixing postNotificationSettings.test.js

- back-end/test/postBlockTag.test.js
- back-end/test/postBlockUser.test.js
> Unit tests for POST /blocktag route handler

- back-end/test/getComments.test.js
> Fixes to unit tests for GET /comments route handler 

- front-end/src/gencomponents/Number.js
- front-end/src/pages/recipepages/components/LargeRecipePreview.css
- front-end/src/pages/recipepages/components/LargeRecipePreview.js
- front-end/src/pages/recipepages/components/SmallRecipePreview.css
- front-end/src/pages/recipepages/components/SmallRecipePreview.js
- front-end/src/pages/recipepages/recipe/RecipePage.css
- front-end/src/pages/recipepages/recipe/RecipePage.js
- front-end/src/pages/userpages/components/SmallUserPreview.css
- front-end/src/pages/userpages/components/SmallUserPreview.js
- front-end/src/pages/userpages/profilepages/mainprofile/components/ProfileHeader.js
> Implement round and format for numbers

- back-end/.dockerignore
- back-end/Dockerfile
- back-end/app.js
- docker-compose.yml
- front-end/Dockerfile
- front-end/nginx.conf
In order to make the container and run it:
`docker-compose up --build`
This should start both the front-end and the back-end with the front-end running on port 80
resolves #451
> Set-up docker container and nginx

- back-end/test/getFeedRecipes.test.js
> Updated unit tests for GET /feedrecipes route handler

- back-end/test/getRecommendedUsers.test.js
> Unit tests for GET /recommendedusers

- back-end/test/getRecommendedRecipes.test.js
> Unit tests for GET /recommendedrecipes

- back-end/test/getUsernameTaken.test.js
> Unit tests for GET /usernametaken

- back-end/package-lock.json
- back-end/package.json
- back-end/test/getFilteredRecipes.test.js
> Updated unit tests for GET /filteredrecipes route handler

- back-end/app.js
- front-end/src/pages/accountpages/settingspage/AppSettings.js
> Fixing blocked users bugs

- back-end/app.js
- front-end/src/App.js
- front-end/src/pages/recipepages/recipe/RecipePage.css
- front-end/src/pages/recipepages/recipe/RecipePage.js
- front-end/src/pages/userpages/userlistpage/UserListPage.js
resolves #466 
- integrate likes into userlistpage (followers/following/likes)
- create GET /likedby route handler to fetch all users that have liked a recipe from the database
- add link to likes page on recipe page
> implement likes page

- back-end/test/postPinRecipe.test.js
> Write unit tests for POST /pinrecipe

- front-end/src/pages/recipepages/recipe/RecipePage.css
> Remove width constraints on recipe page

- back-end/test/getComments.test.js
(using findOne instead of hard coding recipeID in query string)
> fixing GET /comments unit tests

- back-end/app.js
- front-end/src/pages/userpages/profilepages/editprofile/EditProfilePage.js
> save updated bio and last name when fields are empty on edit profile page

- front-end/Dockerfile
The commit was made from the droplet (which is why it says @Dendrobyte wrote it lol)
> Fix Dockerfile

- front-end/src/App.js
- front-end/src/gencomponents/ErrorComponent.js
- front-end/src/gencomponents/ImageCropModal.js
- front-end/src/pages/recipepages/browserecipes/BrowseRecipesPage.js
- front-end/src/pages/recipepages/components/LargeRecipePreview.css
- front-end/src/pages/recipepages/components/SmallRecipePreview.css
- front-end/src/pages/recipepages/feed/FeedPage.js
- front-end/src/pages/recipepages/recipe/RecipePage.css
- front-end/src/pages/recipepages/recipe/RecipePage.js
See commit messages for details
resolves #554
> More bug fixes

- back-end/app.js
(rather than just the default ones)
- resolves #565
> Allowing for uploaded profile pictures to be sent in email notifications

- back-end/Dockerfile
- back-end/app.js
- docker-compose.yml
> Docker now works with uploading/deleting/displaying all images

- .github/workflows/continuous-integration.yml
- README.md
> fixing badge

- .github/workflows/continuous-deployment.yml
- front-end/src/gencomponents/navbar/NavbarAndMenu.css
So I wrote a .yaml file for continuous deployment but I'm unsure of how to test it without merging it into master.
resolves #454
> Set up continuous deployment

- back-end/test/postFollowUser.test.js
> implement post /followuser unit test

- CONTRIBUTING.md
- README.md
Update readme and contributing markdown files for end of class.
> Readme and contributing edit

- front-end/src/App.js
- front-end/src/gencomponents/CreateAccountModal.js
- front-end/src/pages/recipepages/recipe/RecipePage.js
- front-end/src/pages/userpages/profilepages/mainprofile/ProfilePage.js
> Fix create account modal bug

- back-end/app.js
Email link hrefs now match the url that you liked/commented/followed from
resolves #583
> Fix hrefs for email links

- back-end/test/postFollowUser.test.js
resolves #586 
Hopefully when I create this pr, for the first time, I won't get an email saying I followed myself lol.
> Fix POST /followuser unit tests

- back-end/test/postLikeRecipe.test.js
> Fix POST /likerecipe unit tests

- back-end/app.js
- back-end/test/postDeleteComment.test.js
- front-end/src/pages/recipepages/newrecipe/NewRecipePage.js
- front-end/src/pages/recipepages/recipe/Comment.css
- front-end/src/pages/recipepages/recipe/Comment.js
- front-end/src/pages/recipepages/recipe/RecipePage.js
- resolves #581 
- allows user to delete comments that they've posted or any comments within their recipes
- also fixed VSCode warnings coming from NewRecipePage.js
> Delete comments functionality and corresponding unit tests

- back-end/test/getRecipe.test.js
- back-end/test/getRecipesByUser.test.js
- back-end/test/getUsers.test.js
- back-end/test/getUsersById.test.js
- back-end/test/postDeleteRecipe.test.js
- back-end/test/postNewRecipe.test.js
- back-end/test/postUpdateUserInfo.test.js
> fixing warnings in unit tests

- front-end/src/pages/recipepages/newrecipe/NewRecipePage.css
- front-end/src/pages/recipepages/newrecipe/NewRecipePage.js
> functionality for reordering instructions and ingredients

- back-end/app.js
- back-end/db.js
- front-end/src/pages/recipepages/browserecipes/BrowseRecipesPage.js
- front-end/src/pages/recipepages/recipe/Comment.css
- front-end/src/pages/recipepages/recipe/Comment.js
- front-end/src/pages/recipepages/recipe/LikeButton.css
- front-end/src/pages/recipepages/recipe/LikeButton.js
- front-end/src/pages/recipepages/recipe/RecipePage.css
- front-end/src/pages/recipepages/recipe/RecipePage.js
- front-end/src/pages/userpages/userlistpage/UserList.css
- front-end/src/pages/userpages/userlistpage/UserList.js
- front-end/src/pages/userpages/userlistpage/UserListModal.css
- front-end/src/pages/userpages/userlistpage/UserListModal.js
- front-end/src/pages/userpages/userlistpage/UserListPage.css
- front-end/src/pages/userpages/userlistpage/UserListPage.js
> User story/600/task/606/implement comment likes and replies
